// qr/src/shared/components/MovieBottomInfo/MovieBottomInfo.jsx
import style from './moviebottominfo.module.scss'
import {useSelector} from "react-redux";
import {Link, useNavigate} from "react-router-dom";
import {AddToQueueBtn} from "@/shared/components/AddToQueueBtn/AddToQueueBtn.jsx";
import mainActive from '@/assets/images/mainActive.svg'


export const MovieBottomInfo = ({item}) => {
    const clientString = localStorage.getItem('client');
    const client = clientString ? JSON.parse(clientString) : null;
    const clLocation = client?.location || null;
    const id = client?.id || null;
    const userId = clLocation && id ? `${clLocation}/${id}` : null;
    const paidFilms = useSelector((state) => state.paidFilms.paidFilms);
    const isInPaidFilms = paidFilms.some(film => film.film_id === item.film_id);

    const navigate = useNavigate()

    const handleClick = () => {
        if (isInPaidFilms) {
            navigate('/films');
        } else {
            navigate('/queue')
        }
    }

    const queue = useSelector((state) => state.queue.queue);

    const styles = {
        width: '21.6417vw',
        height: '11.19vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'rgba(255,255,255, 0.37)',
        borderRadius: '30px',
    }

    const stylesNone = {
        width: '21.6417vw',
        height: '11.19vw',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'rgba(255,255,255, 0.37)',
        borderRadius: '30px',
        color: '#171717',
        cursor: 'not-allowed',
        pointerEvents: 'none',
        opacity: '0.3'
    }

    const disabledStyles = {
        opacity: '0.3',
        cursor: 'not-allowed',
        pointerEvents: 'none',
    };

    const isQueueEmpty = queue.length === 0;

    return (
        <div className={style.movieBottomInfo}>
            <div className={style.upperInfo}>
                <div className={style.name}>
                    {item.name_short}
                </div>
                <div className={style.titleWithBtn}>
                    <div className={style.price}>
                        {item.price}₽
                    </div>
                    <div className={style.linkContainer}>
                        <Link to={`/vr/${userId}`}>
                            <div style={styles} className={style.home}>
                                <img src={mainActive} alt='main'/>
                            </div>
                        </Link>
                    </div>
                </div>
                <div className={style.btns}>
                    <div onClick={handleClick} className={style.toQueue}
                         style={isQueueEmpty && !isInPaidFilms ? disabledStyles : {}}>
                        {isInPaidFilms ? <>К покупкам</> : <>Перейти в корзину</>}
                    </div>
                    <AddToQueueBtn item={item} styles={item.serial || isInPaidFilms ? stylesNone : styles}/>
                </div>
            </div>
            <div className={style.bottomInfo}>
                <div className={style.upper}>
                <div className={style.filmName}>
                        <div className={style.infoUpperPar}>
                            <div className={style.par}>Название</div>
                            <div className={style.parDescr}>{item.country}</div>
                        </div>
                        <div className={style.infoUpperPar}>
                            <div className={style.par}>Год</div>
                            <div className={style.parDescr}>{item.year}</div>
                        </div>
                    </div>
                </div>
                <div className={style.middle}>
                    <div className={style.par}>
                        Описание
                    </div>
                    <div className={style.parDescr}>
                        {item.description}
                    </div>
                </div>
                <div className={style.upper} style={{marginBottom: '3.7313vw'}}>
                    <div className={style.filmName}>
                        <div className={style.infoUpperPar}>
                            <div className={style.par}>Длительность</div>
                            <div className={style.parDescr}>{item.time}</div>
                        </div>
                        <div className={style.infoUpperPar}>
                            <div className={style.par}>Цена</div>
                            <div className={style.parDescr}>{item.price}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

// qr_svelte5/src/lib/components/SingleMovieItem/MovieBottomInfo.svelte
<script>
  import { goto } from '$app/navigation';
  import { globals } from '$lib/stores/+stores.svelte.js';
  import { icons } from '$lib/icons/icons.js';
  import LOCAL_STORAGE_KEYS from '$lib/constants/localStorageKeys.js';
  import AddToQueueBtn from './AddToQueueBtn.svelte';

  let { item } = $props();

  let paidFilms = $derived(globals.get('paidFilms'));
  let queue = $derived(globals.get('queue'));

  function getCurrentClient() {
    const clientString = localStorage.getItem(LOCAL_STORAGE_KEYS.CLIENT);
    const client = clientString ? JSON.parse(clientString) : null;
    const clLocation = client?.location || null;
    const id = client?.id || null;
    return clLocation && id ? `${clLocation}/${id}` : null;
  }

  let isInPaidFilms = $derived(() => {
    return paidFilms.some(film => film.film_id === item.film_id);
  });

  let isQueueEmpty = $derived(() => {
    return queue.length === 0;
  });

  function handleClick() {
    if (isInPaidFilms()) {
      goto('/films');
    } else {
      goto('/queue');
    }
  }

  function handleHomeClick() {
    const userId = getCurrentClient();
    goto(`/vr/${userId}`);
  }

  const styles = {
    width: '21.6417vw',
    height: '11.19vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--color-white-37)',
    borderRadius: 'var(--radius-30)',
  };

  const stylesNone = {
    width: '21.6417vw',
    height: '11.19vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--color-white-37)',
    borderRadius: 'var(--radius-30)',
    color: 'var(--color-dark-primary)',
    cursor: 'not-allowed',
    pointerEvents: 'none',
    opacity: '0.3'
  };

  const disabledStyles = {
    opacity: '0.3',
    cursor: 'not-allowed',
    pointerEvents: 'none',
  };
</script>

<div class="movie-bottom-info">
  <div class="upper-info">
    <div class="name">
      {item.name_short}
    </div>
    <div class="title-with-btn">
      <div class="price">
        {item.price}₽
      </div>
      <div class="link-container">
        <div class="home" onclick={handleHomeClick}>
          {@html icons.mainActive}
        </div>
      </div>
    </div>
    <div class="btns">
      <div 
        class="to-queue" 
        onclick={handleClick}
        style={isQueueEmpty() && !isInPaidFilms() ? Object.entries(disabledStyles).map(([k, v]) => `${k}: ${v}`).join('; ') : ''}
      >
        {isInPaidFilms() ? 'К покупкам' : 'Перейти в корзину'}
      </div>
      <AddToQueueBtn 
        {item} 
        styles={item.serial || isInPaidFilms() ? stylesNone : styles} 
      />
    </div>
  </div>
  <div class="bottom-info">
    <div class="upper">
      <div class="film-name">
        <div class="info-upper-par">
          <div class="par">Название</div>
          <div class="par-descr">{item.country}</div>
        </div>
        <div class="info-upper-par">
          <div class="par">Год</div>
          <div class="par-descr">{item.year}</div>
        </div>
      </div>
    </div>
    <div class="middle">
      <div class="par">
        Описание
      </div>
      <div class="par-descr">
        {item.description}
      </div>
    </div>
    <div class="upper" style="margin-bottom: 3.7313vw;">
      <div class="film-name">
        <div class="info-upper-par">
          <div class="par">Длительность</div>
          <div class="par-descr">{item.time}</div>
        </div>
        <div class="info-upper-par">
          <div class="par">Цена</div>
          <div class="par-descr">{item.price}₽</div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .movie-bottom-info {
    width: 95.0248vw;
    display: flex;
    flex-direction: column;
    gap: 4.9751vw;
  }

  .upper-info {
    display: flex;
    flex-direction: column;
    font-weight: 400;
    font-size: 5.9701vw;
    color: var(--color-white);
    font-family: "Manrope", serif;
    gap: 2.4875vw;
  }

  .price {
    padding-right: 2px;
    padding-left: 2px;
    border-bottom: 1px solid white;
    width: fit-content;
    margin-bottom: 2.4875vw;
  }

  .btns {
    display: flex;
    justify-content: space-between;
  }

  .to-queue {
    width: 70.6467vw;
    height: 11.19vw;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 400;
    font-size: 3.99vw;
    background: var(--color-white-90);
    border-radius: var(--radius-30);
    color: var(--color-dark-primary);
    font-family: "Montserrat", serif;
    cursor: pointer;
  }

  .btn-add {
    width: 21.6417vw;
    height: 11.19vw;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--color-white-37);
    border-radius: var(--radius-30);
  }

  .bottom-info {
    width: 100%;
    height: fit-content;
    background: var(--color-dark-secondary);
    border-radius: var(--radius-5);
    font-family: "Montserrat", serif;
    display: flex;
    flex-direction: column;
    gap: 2.98507vw;
  }

  .upper {
    margin-top: 3.7313vw;
    margin-left: 3.7313vw;
    margin-right: 3.7313vw;
  }

  .middle {
    margin-left: 3.7313vw;
    margin-right: 3.7313vw;
    display: flex;
    flex-direction: column;
    gap: 3.2338vw;
  }

  .film-name {
    display: flex;
    gap: 13.4328vw;
  }

  .info-upper-par {
    display: flex;
    flex-direction: column;
    gap: 3.2338vw;
  }

  .par {
    font-weight: 500;
    font-size: 4.2288vw;
    color: var(--color-white-65);
  }

  .par-descr {
    font-weight: 500;
    font-size: 3.7313vw;
    color: var(--color-white);
  }

  .title-with-btn {
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: center;
    height: fit-content;
  }

  .home {
    width: 7.4627vw;
    height: 7.4627vw;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--color-white-10);
    border-radius: var(--radius-full);
    cursor: pointer;
    transition: var(--transition-100);
  }

  .home:hover {
    background: var(--color-white-20);
  }

  .home :global(svg) {
    height: auto;
  }

  .name {
    height: 100%;
    display: flex;
    align-self: start;
  }

  .link-container {
    align-self: end;
  }
</style>
